/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { RNG } from "../RNG";

export class RNG__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<RNG> {
    return super.deploy(overrides || {}) as Promise<RNG>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): RNG {
    return super.attach(address) as RNG;
  }
  connect(signer: Signer): RNG__factory {
    return super.connect(signer) as RNG__factory;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): RNG {
    return new Contract(address, _abi, signerOrProvider) as RNG;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "seed",
        type: "uint256",
      },
    ],
    name: "generateRandomNumber",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x60806040526000805534801561001457600080fd5b5061017d806100246000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80634303707e14610030575b600080fd5b61004361003e3660046100e9565b610055565b60405190815260200160405180910390f35b600060016000808282546100699190610102565b90915550506000543342844461008060014361011a565b406040516020016100cb9695949392919095865260609490941b6bffffffffffffffffffffffff19166020860152603485019290925260548401526074830152609482015260b40190565b60408051601f19818403018152919052805160209091012092915050565b6000602082840312156100fb57600080fd5b5035919050565b6000821982111561011557610115610131565b500190565b60008282101561012c5761012c610131565b500390565b634e487b7160e01b600052601160045260246000fdfea2646970667358221220ad3926d5bfc74358820457a819da898076b8116c556406b8fb8dfaf20b4b0b2e64736f6c63430008050033";
