/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface RNGTestInterface extends ethers.utils.Interface {
  functions: {
    "generate(uint256)": FunctionFragment;
    "number()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "generate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "number", values?: undefined): string;

  decodeFunctionResult(functionFragment: "generate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "number", data: BytesLike): Result;

  events: {};
}

export class RNGTest extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: RNGTestInterface;

  functions: {
    generate(
      seed: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "generate(uint256)"(
      seed: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    number(overrides?: CallOverrides): Promise<[BigNumber]>;

    "number()"(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  generate(
    seed: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "generate(uint256)"(
    seed: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  number(overrides?: CallOverrides): Promise<BigNumber>;

  "number()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    generate(seed: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "generate(uint256)"(
      seed: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    number(overrides?: CallOverrides): Promise<BigNumber>;

    "number()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    generate(seed: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "generate(uint256)"(
      seed: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    number(overrides?: CallOverrides): Promise<BigNumber>;

    "number()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    generate(
      seed: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "generate(uint256)"(
      seed: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    number(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "number()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
